#! /bin/sh
# /etc/init.d/enphase2influx
### BEGIN INIT INFO
# Provides:          enphase2influx
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Service for logging enphase local data to influxdb
### END INIT INFO

case "$1" in
  start)
    log_begin_msg "Starting enphase2influx service"
    /usr/local/bin/enphase2influx/enphase2influx_15sec.sh &
    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Stopping enphase2influx service"

    # do something to kill the service or cleanup or nothing
    killall enphase2influx_15sec*
    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/enphase2influx {start|stop}"
    exit 1
    ;;
esac 
